meta_product_name: "Couch Beef"
meta_title: "Couch Beef - Earn money doing what you love most."
meta_description: "Earn money playing your favourite e-games against opponents from around the globe"
meta_image: "beef2.png" # should exist in `app/assets/images/`
